version: "3.3"

services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    container_name: pixel-art-backend
    networks:
      - webappnetwork

  client:
    stdin_open: true
    build: ./frontend/pixel-art
    ports:
      - "3000:3000"
    container_name: pixel-art-frontend
    depends_on:
      - backend
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge